[build]
  publish = "public"
  functions = "netlify/functions"

# Ensure clean pass-through for Netlify Functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
