#############################################
# WasfaOne — Netlify configuration
# - Publish static site from /public
# - Serverless functions from /netlify/functions
# - Friendly rewrites for app pages
# - Safe defaults for CORS & caching of dynamic data
#############################################

[build]
  publish   = "public"
  functions = "netlify/functions"

#############################################
# Redirects / Rewrites (200 = SPA-style)
#############################################

# Home
[[redirects]]
  from   = "/"
  to     = "/public/index.html"
  status = 200

# Pretty paths for main pages
[[redirects]]
  from   = "/app"
  to     = "/public/app.html"
  status = 200

[[redirects]]
  from   = "/login"
  to     = "/public/login.html"
  status = 200

[[redirects]]
  from   = "/signup"
  to     = "/public/signup.html"
  status = 200

[[redirects]]
  from   = "/admin"
  to     = "/public/admin.html"
  status = 200

# 404 fallback (keeps your /public/404.html)
[[redirects]]
  from   = "/*"
  to     = "/public/404.html"
  status = 404

#############################################
# Headers
#############################################

# Security & baseline headers for all static assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "strict-origin-when-cross-origin"
    Permissions-Policy     = "accelerometer=(), autoplay=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=()"
    # Static assets may be cached by browser; HTML typically revalidated by the browser heuristics.
    # You can fine-tune per-path below for data / functions.
    Cache-Control          = "public, max-age=600"

# Ensure dynamic JSON under /data is not cached aggressively on the client
[[headers]]
  for = "/data/*"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "no-store, max-age=0, must-revalidate"

# Functions: CORS-friendly defaults (functions themselves set headers too)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "GET, POST, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-Admin-Auth, X-Auth-Token, X-Session-Nonce"
    Cache-Control = "no-store, max-age=0, must-revalidate"

#############################################
# Notes
# - Environment variables (GITHUB_TOKEN, GITHUB_REPO_OWNER, GITHUB_REPO_NAME,
#   GITHUB_REF, ADMIN_PASSWORD, GEMINI_API_KEY) should be set in Netlify UI.
# - Functions already include their own CORS/security headers; these are safe defaults.
#############################################
